services:
  redis: 
    image: redis:7.2.5-alpine3.19
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    networks:
      - pse_analyzer_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  db:
    image: mysql:8.0.37-bookworm
    container_name: db
    restart: always
    ports:
      - 3307:3307
    env_file: .env
    volumes:
      - mysql_volume_data:/var/lib/mysql
    networks:
      - pse_analyzer_network
  api:
    build: .
    ports:
      - 8080:8080
    env_file: .env
    container_name: api
    networks:
      - pse_analyzer_network
    depends_on:
      - redis
      - db
networks:
  pse_analyzer_network:
volumes:
  redis_volume_data: 
  mysql_volume_data:
